server:
  port: 8001
spring:
  datasource:
    url: jdbc:h2:mem:GroceryInventorydb
    driver-class-name: org.h2.Driver
    username: Admin
    password: Inventory
  h2:
    console:
      enabled: true
